name: Build on Bitbucket webhook

on:
  repository_dispatch:
    types: [bitbucket_event]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Clone Bitbucket repository
        run: |
          git clone https://${{ secrets.BITBUCKET_USERNAME }}:${{ secrets.BITBUCKET_APP_PASSWORD }}@bitbucket.org/github_webhook/maven-sample.git
          cd maven-sample
        shell: bash

      - name: Build with Maven
        run: |
          cd maven-sample/sample
          mvn clean install
        shell: bash

